version: '3.8'
services:
  consul:
    image: progrium/consul
    ports:
      - "8500:8500"
    environment:
      CONSUL_BIND_INTERFACE: eth0
    volumes:
      - consul_data:/data

  myapp:
    image: myapp:latest
    build:
      context: .
    depends_on:
      - consul
    environment:
      CONSUL_HOST: consul
    ports:
      - "8080:8080"

volumes:
  consul_data:
