version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roshi-app
    ports:
      - "8080:8080"
    depends_on:
      consul:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul

  consul:
    image: consul:1.15.4
    container_name: dev-consul
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - ./consul_data:/consul/data
    command: agent -server -bootstrap-expect=1 -client 0.0.0.0 -ui -data-dir=/consul/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8500/v1/status/leader" ]
      interval: 10s
      timeout: 5s
      retries: 5
